### ISSUE TITLE
co-maintainers lists duplicates for split packages

### ISSUE THREAD

**Issue by kyrias** [archlinux/contrib#12]
The output for me returns f.ex. `mediainfo` and `mediainfo-gui`, which belong to the same split package, leading to two `mediainfo` pkgbases in the output.

Either `find_packages` should return pkgbases, or a unique filter should be added to the final output.

**Comment by Foxboron** [comment]
So the problem is that we can't easily query pkgbases for split packages in archweb, there is no json and the page just returns HTML. Should rather add some unique filter.

**Comment by Foxboron** [comment]
The trick is to output `.repo .arch .pkgname .pkgbase` and then use `sort -u -k4,4` to remove duplicate pkgbases.
