### ISSUE TITLE
have offload-build copy packages to package folder (PKGDEST)

### ISSUE THREAD

**Issue by kgizdov** [archlinux/contrib#2]
@eli-schwartz can we get offload-build{-new} to copy files to PKGDEST on the initiating machine?

**Comment by coderobe** [comment]
I think this'll do:

https://github.com/archlinux/contrib/blob/74ce2925fd480b2a1751169c0404db3ef29eb7ae/build/offload-build-new#L100
->
```bash
 (( ${#files[@]} )) && printf '%s\n' '' '-> copying files...' && scp "${files[@]/#/$server:}" ${PKGDEST:-.}
```

**Comment by kgizdov** [comment]
@coderobe I think we also need to make `PKGDEST` available by calling `makepkg` or something.

**Comment by kgizdov** [comment]
maybe just:
```bash
MAKEPKG_CONF=${/etc/makepkg.conf:-$XDG_CONFIG_HOME/pacman/makepkg.conf}
source ${MAKEPKG_CONF:-$HOME/.makepkg.conf}
```

**Comment by coderobe** [comment]
Ah yes, that will never evaluate to `$XDG_CONFIG_HOME/pacman/makepkg.conf` nor `$HOME/.makepkg.conf` though, only ever to `/etc/makepkg.conf` - so a big part of that seems to be redundant. Unless i'm missing something here

**Comment by eli-schwartz** [comment]
```
$ MAKEPKG_CONF=${/etc/makepkg.conf:-$XDG_CONFIG_HOME/pacman/makepkg.conf}
bash: ${/etc/makepkg.conf:-$XDG_CONFIG_HOME/pacman/makepkg.conf}: bad substitution
```

That's not even a valid bash language construct. "/etc/makepkg.conf" is not allowed as a variable *name*.

It will evaluate to a syntax error.

**Comment by kgizdov** [comment]
please check up to date branch, it was a work in progress before, but now uses `makepkg` and gets correct path.

**Comment by Foxboron** [comment]
Since `offload-build` has moved to devtools
