### ISSUE TITLE
checkservices: broken parsing of systemctl output

### ISSUE THREAD

**Issue by lahwaacz** [archlinux/contrib#29]
It seems that my fix in #20 was not the best - the systemctl command does not print only leading spaces, but the first character can be an arbitrary "mark":
```
$ systemctl --no-legend --full --type service --state running
  dbus.service                   loaded    active running D-Bus System Message Bus
  nginx.service                  loaded    active running A high performance web server and a reverse proxy server
● org.cups.cupsd.service         not-found active running org.cups.cupsd.service
  polkit.service                 loaded    active running Authorization Manager
...
```
So passing it to `awk '{print $1}'` will give `●` instead of `org.cups.cupsd.service` which is not a valid unit name.

**Comment by Foxboron** [comment]
`systemctl --no-legend --full --type service --state running | tr -d ● | awk '{print $1}'`

My quick fix

**Comment by lahwaacz** [comment]
Thanks, I made a PR for it. Let's hope systemd won't change their fancy output again/soon...
