### ISSUE TITLE
checkservices: cgroup v2 base path

### ISSUE THREAD

**Issue by lahwaacz** [archlinux/contrib#34]
checkservices currently checks `/sys/fs/cgroup/systemd` as the cgroup base path: https://github.com/archlinux/contrib/blob/48e9539aaf6cf8f47f7b0d232c0b2a9701adecd7/admin/checkservices#L31

However, if the cgroup v2 hierarchy is used, `/sys/fs/cgroup/systemd` does not exist and systemd uses `/sys/fs/cgroup` directly.

**Comment by Foxboron** [comment]
That probably solves it?

**Comment by lahwaacz** [comment]
Yes, seems it does.
