### ISSUE TITLE
checkservices: Unable to parse pid file for getty@tty1.service

### ISSUE THREAD

**Issue by cloudlena** [archlinux/contrib#44]
When running `checkservices`, I am getting the following error:

```shell
$ sudo checkservices
:: Run pacdiff
:: Reload systemd
:: Services with broken maps files
Error:: Unable to parse pid file for getty@tty1.service.
Found: 0
:: Services missing on the system bus
Found: 0
:: List failed units
```

Am I doing something wrong? This seems like a common service to have.

**Comment by lahwaacz** [comment]
`checkservices` started as a script for headless servers where people log in only via SSH. In case you log in via a graphical display manager, `checkservices` might detect that it needs to be restarted, which would terminate the entire session. Same for `polkit.service`, `systemd-logind.service` and maybe others (IIRC). The missing PID file for `getty@tty1.service` just coincidentally avoids this.

**Comment by mastertinner** [comment]
@lahwaacz, thanks a lot for the clarification! Is there any sensible way to deal with this? I'm running Arch with [Sway](https://github.com/swaywm/sway).

**Comment by aminvakil** [comment]
What do you think about asking for confirmation (Are you sure?) if it wants to run on a graphical arch?

I can create a PR for this.

**Comment by Foxboron** [comment]
I'd rather we have a list of ignored services and add things like getty@tty.service to it.

**Comment by lahwaacz** [comment]
> What do you think about asking for confirmation (Are you sure?) if it wants to run on a graphical arch?

`checkservices` already asks for confirmation before restarting services, but all services are grouped and restarted together...

**Comment by aminvakil** [comment]
> I'd rather we have a list of ignored services and add things like [getty@tty.service](mailto:getty@tty.service) to it.

I'm not sure, aren't there other services which may break by restarting in a desktop environment?

> > What do you think about asking for confirmation (Are you sure?) if it wants to run on a graphical arch?
> 
> `checkservices` already asks for confirmation before restarting services, but all services are grouped and restarted together...

I was thinking of check the output of `systemctl get-default` and warn again if it's `graphical.target`.

**Comment by lahwaacz** [comment]
> I was thinking of check the output of `systemctl get-default` and warn again if it's `graphical.target`.

You can have an active session, graphical or not, even with plain `multi-user.target`.

**Comment by Foxboron** [comment]
We are straying a bit from the issue. Keeping track of pid-less services is the goal, and this should be fairly simple to have as a filtered list in the code and omit them from the get_services code.

@aminvakil did you want to try implement this?

**Comment by Foxboron** [comment]
I don't think so?

```
λ ~ » systemctl show getty@tty1.service | grep PID
GuessMainPID=yes
MainPID=404
ControlPID=0
ExecMainPID=404
λ ~ » systemctl show bolt.service | grep PID
GuessMainPID=yes
MainPID=1406
ControlPID=0
ExecMainPID=1406
```

**Comment by aminvakil** [comment]
```
$ sudo systemctl show getty@tty1.service | grep PID
GuessMainPID=yes
MainPID=0
ControlPID=0
ExecMainPID=0
$ sudo systemctl show bolt.service | grep PID
GuessMainPID=yes
MainPID=0
ControlPID=0
ExecMainPID=0
```
Can this maybe somehow be related to `linux-hardened`?

**Comment by mastertinner** [comment]
If it helps, I'm not using `linux-hardened`, just bare bones `linux`.

**Comment by aminvakil** [comment]
> If it helps, I'm not using `linux-hardened`, just bare bones `linux`.

Honestly I really don't think so, this is just a wild guess, and I meant returning 0 for `MainPID` when `linux-hardened` is used.

**Comment by lahwaacz** [comment]
@aminvakil Obviously, if you don't have `getty@tty1.service` active, systemctl shows its `MainPID` as 0.

**Comment by aminvakil** [comment]
@lahwaacz Sorry for late response, yes, it was not active.
