### ISSUE TITLE
rebuild-todo: commiting straight to [core] is disallowed

### ISSUE THREAD

**Issue by anthraxx** [archlinux/contrib#57]
[core] packages must go through [testing], hence the default target should be [testing] without a possibility to commit straight to [core]

**Comment by alerque** [comment]
Not being a developer I don't have experience managing [core] packages, but does `pkgctl build` and `pkgctl release` automatically enforce this workflow? If it doesn't it seems like it should, and as of today's release of `rebuild-todo` then if that is enforced on the `pkgctl` side then it should automatically work in the todo builder as well.

**Comment by Antiz96** [comment]
@alerque Yes, this workflow is enforced by `pkgctl`. Unless I'm missing something, now that `rebuild-todo` makes us of `pkgctl`, I think this issue is outdated and can be close.

**Comment by jelly** [comment]
This used commitpkg before which would allow it.
