### ISSUE TITLE
Checkservices: False positive on firewalld.service

### ISSUE THREAD

**Issue by Antiz96** [archlinux/contrib#76]
`firewalld.service` will always be reported as having broken maps files and needed to be restarted by `checkservices`, regardless if it was already restarted earlier or not (or even upgraded at all). By looking at the script, it seems like `checkervices` does some [grepping/parsing](https://github.com/archlinux/contrib/blob/master/admin/checkservices#L139) to `/proc/"pid of the service"/maps` to determine the list of services with deleted maps files. For some reason, `firewalld.service` will **always** report one as deleted, causing a false positive:

![image](https://github.com/user-attachments/assets/29019106-0d18-4c4e-a293-9104aa707f87)

Unfortunately, I don't have enough knowledge on this to understand if the issue is on the firewalld side, the libffi one or if it's the [grepping/parsing](https://github.com/archlinux/contrib/blob/master/admin/checkservices#L139) part of `checkservices` that should be made more "robust" somehow. Maybe someone we'll be able to understand what's wrong here?

**Comment by lahwaacz** [comment]
I've noticed this too, seems to be happening only since the last upgrade (of something :angel:)

**Comment by Antiz96** [comment]
> I've noticed this too, seems to be happening only since the last upgrade (of something 👼)

Oh, well... I upgraded both archlinux-contrib and firewalld recently so... :angel: If you're positive it started only since the last upgrade of something, downgrading them might worth a shot!

I'll try that in a few.

**Comment by Antiz96** [comment]
Actually, checkservices was last modified [2 years ago](https://github.com/archlinux/contrib/commits/master/admin/checkservices) so it's most probably not the cause. I'll try downgrading firewalld in a minute to see if it helps.

**Comment by lahwaacz** [comment]
It seems to be related to this systemd service hardening: https://github.com/firewalld/firewalld/commit/1632f93544be8a26c278ac0012993c27f865bfa3

**Comment by Antiz96** [comment]
Thanks, I'm including that in my upstream report.

**Comment by lahwaacz** [comment]
I'm thinking we should actually skip the `/memfd:` lines from the maps in the checkservices handling... But asking should not hurt
